### ISSUE TITLE
Don't show follow button for self.

### ISSUE THREAD

**Issue by Wopian** [hummingbird-me/hummingbird#362] opened 2015-01-12 22:51 UTC
Orange follow button is visible on your own permalinks and on other people's follow(er/ing) pages.

Occurs in:

- [user/followers](https://github.com/hummingbird-me/hummingbird/blob/master/app/frontend/app/templates/user/followers.hbs)
- [user/following](https://github.com/hummingbird-me/hummingbird/blob/master/app/frontend/app/templates/user/following.hbs)
- [story/permalink](https://github.com/hummingbird-me/hummingbird/blob/master/app/frontend/app/templates/story/permalink.hbs)

Anywhere else I'm missing?

**Comment by NuckChorris** [comment] 2015-01-12 23:10
Is there one of these on review pages?

**Comment by Wopian** [comment] 2015-01-13 01:20
@NuckChorris yup

![](http://a.pomf.se/urjjnu.png)

**Comment by cybrox** [comment] 2015-01-13 06:16
Basically duplicate of #316, since @vikhyat's soloution would solve the problem.

**Closed** 2015-01-13 08:08 UTC
